import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Info from '../containers/Info'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>

      <Head>
        <title>Titre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Info/>
      </main>

    </div>
  )
}


export default Home
